### ISSUE TITLE
Analysis & training -> Error of top terms calculation after filtering

### ISSUE THREAD

**Issue by AnkaGromova** [exactpro/nostradamus#13]
Steps to reproduce:
1) Download soa1.xml file
2) Conduct filtering  "resolution = incomplete description"
3) Apply

Expected Result:
 Successful filtering. 1 bug is found.

Actual result:
Error  "ValueError: empty vocabulary; perhaps the documents only contain stop words."

**Comment by il1tvinov** [comment]
**Resolved in v6.2.2**
