### ISSUE TITLE
Assets missing

### ISSUE THREAD

**Issue by herleswarna** [exactpro/nostradamus#18]
When I try to build the project, building of react application fails.

It seems that there should be two folders with images `assets/images` and `assets/icons` which are not present.

Am I missing some part of setup or are they missing by a mistake?

**Comment by il1tvinov** [comment]
Hello @herleswarna 

Thanks a lot for the issue.
These files were definetely missed by a mistake. We've fixed that in the latest release [v7.7.1](https://github.com/exactpro/nostradamus/releases/tag/7.7.1)

Please pull the new changes and don't hesitate to ask me any questions.

**Comment by il1tvinov** [comment]
@herleswarna can we close the issue?

**Comment by herleswarna** [comment]
Hello,

Thank you. Yes you can close the issue.

Regards,
Swarna

**Comment by il1tvinov** [comment]
Thanks a lot @herleswarna 
Please don't hesitate to ask me any other questions.

Happy Friday 🙌🏽
