### ISSUE TITLE
Single Description > Size and background colour of description field are changed after choice of highlighting type

### ISSUE THREAD

**Issue by AnkaGromova** [exactpro/nostradamus#8]
Steps to reproduce:
1. Log into system.
2. Open Single Description mode.
3. Enter any description.
4. Click on an empty space
5. Choose any type of highlighting.

Expected result:
Description is highlighted correctly.

Actual result:
Background colour is changed to gray.
Description field size is changed a bit.

**Comment by il1tvinov** [comment]
### Resolved in v6.2.1
Text area has fixed size
